using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;

using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Media.Imaging;

using Windows.Graphics.Imaging;
using Windows.Storage;
using Windows.Storage.Streams;
using HackPDM.Helper.Compatibility;
using SB = HackPDM.StorageBox;
using HackPDM.Src.ClientUtils.Types;

namespace HackPDM.Properties;

internal partial class Settings : ApplicationSettingsBase
{
	public static ISettingsProvider Provider { get; } = GetProvider();

	private static ISettingsProvider GetProvider()
	{
		var os = Environment.OSVersion.Version;
#pragma warning disable CA1416 // Validate platform compatibility
		return os.Major >= 10
			? new ModernSettingsProvider()
			: new LegacySettingsProvider();
#pragma warning restore CA1416 // Validate platform compatibility
	}

	public static T? Get<T>(string key, T? defaultValue = default)
	{
		try
		{
			return Provider.Get(key, defaultValue);
		}
		catch
		{
			return default;
		}
	}
	public static void Set<T>(string key, T value) => Provider.Set(key, value);
}
internal static class Assets
{
	internal static readonly Dictionary<string, string> AssetMap;
	internal static StorageFolder Storage => ApplicationData.Current.LocalFolder;

	static Assets()
	{
		AssetMap = new Dictionary<string, string>
		{
			{ "delete_image_button",							$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/delete_image_button.png" },
			{ "hackpdm-icon",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/hackpdm-icon.ico" },
			{ "loading",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/loading.gif" },
			{ "LockScreenLogo.scale-200",						$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/LockScreenLogo.scale-200.png" },
			{ "SplashScreen.scale-200",							$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/SplashScreen.scale-200.png" },
			{ "Square150x150Logo.scale-200",					$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/Square150x150Logo.scale-200.png" },
			{ "Square44x44Logo.scale-200",						$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/Square44x44Logo.scale-200.png" },
			{ "Square44x44Logo.targetsize-24_altform-unplated", $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/Square44x44Logo.targetsize-24_altform-unplated.png" },
			{ "square_empty",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/square_empty.png" },
			{ "StoreLogo",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/StoreLogo.png" },
			{ "UnknownImage",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/UnknownImage.png" },
			{ "Wide310x150Logo.scale-200",						$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/Wide310x150Logo.scale-200.png" },
			{ "3mf",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/3mf.png" },
			//{ "ai",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/ai.png" },
			{ "asmdot",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/asmdot.png" },
			{ "asmprp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/asmprp.png" },
			//{ "avi",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/avi.png" },
			//{ "bas",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/bas.png" },
			//{ "bat",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/bat.png" },
			//{ "bmp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/bmp.png" },
			//{ "btl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/btl.png" },
			//{ "cnc",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/cnc.png" },
			//{ "cs",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/cs.png" },
			//{ "csproj",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/csproj.png" },
			//{ "csv",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/csv.png" },
			//{ "cwr",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/cwr.png" },
			//{ "dat",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/dat.png" },
			//{ "db",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/db.png" },
			//{ "default",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/default.png" },
			//{ "dic",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/dic.png" },
			//{ "doc",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/doc.png" },
			//{ "docx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/docx.png" },
			//{ "dot",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/dot.png" },
			//{ "drwdot",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/drwdot.png" },
			//{ "dwg",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/dwg.png" },
			//{ "dxf",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/dxf.png" },
			//{ "edrw",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/edrw.png" },
			//{ "eps",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/eps.png" },
			//{ "gcode",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/gcode.png" },
			//{ "gif",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/gif.png" },
			//{ "gz",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/gz.png" },
			//{ "htm",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/htm.png" },
			//{ "igs",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/igs.png" },
			//{ "indd",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/indd.png" },
			//{ "index",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/index.png" },
			//{ "jpg",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/jpg.png" },
			//{ "ldb",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/ldb.png" },
			//{ "log",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/log.png" },
			//{ "m",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/m.png" },
			//{ "mdb",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/mdb.png" },
			//{ "ods",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/ods.png" },
			//{ "odt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/odt.png" },
			//{ "pdf",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/pdf.png" },
			//{ "png",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/png.png" },
			//{ "propdesc",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/propdesc.png" },
			//{ "prtdot",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/prtdot.png" },
			//{ "prtprp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/prtprp.png" },
			//{ "ps",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/ps.png" },
			//{ "resx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/resx.png" },
			//{ "rpt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/rpt.png" },
			{ "settings",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/settings.png" },
			//{ "sla",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/sla.png" },
			//{ "sldasm",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/sldasm.png" },
			//{ "sldprt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/sldprt.png" },
			//{ "slddrw",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/slddrw.png" },
			
			{ "sldblk",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldblk.svg" },
			{ "sldbomtbt",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldbomtbt.svg" },
			{ "slddrt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/slddrt.svg" },
			{ "sldedb",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldedb.svg" },
			{ "sldedbold",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldedbold.svg" },
			{ "sldgtolfvt",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldgtolfvt.svg" },
			{ "sldholtbt",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldholtbt.svg" },
			{ "sldlfp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldlfp.svg" },
			{ "sldmtnfvt",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldmtnfvt.svg" },
			{ "sldpuntbt",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldpuntbt.svg" },
			{ "sldrevtbt",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldrevtbt.svg" },
			{ "sldsffvt",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldsffvt.svg" },
			{ "sldtbt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldtbt.svg" },
			{ "sldweldfvt",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldweldfvt.svg" },
			{ "sldwldtbt",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldwldtbt.svg" },
			
			//{ "sln",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/sln.png" },
			//{ "sqy",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/sqy.png" },
			//{ "suo",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/suo.png" },
			//{ "svg",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/svg.png" },
			//{ "swp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/swp.png" },
			//{ "sym",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/sym.png" },
			//{ "tbox",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/tbox.png" },
			//{ "tif",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/tif.png" },
			//{ "ttf",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/ttf.png" },
			//{ "txt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/txt.png" },
			//{ "wxm",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/wxm.png" },
			//{ "wxmx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/wxmx.png" },
			//{ "xls",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/xls.png" },
			//{ "xlsx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/xlsx.png" },
			//{ "xml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/xml.png" },
			//{ "x_b",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/x_b.png" },
			//{ "x_t",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/x_t.png" },
			//{ "zip",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.EXTENSIONFOLDER}/zip.png" },
			//{ "folder-icon_checkedme_32",						$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.FOLDERICONS}/folder-icon_checkedme_32.gif" },
			//{ "folder-icon_checkedother_32",					$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.FOLDERICONS}/folder-icon_checkedother_32.gif" },
			//{ "folder-icon_deleted_32",							$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.FOLDERICONS}/folder-icon_deleted_32.gif" },
			//{ "folder-icon_localonly_32",						$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.FOLDERICONS}/folder-icon_localonly_32.gif" },
			//{ "folder-icon_remoteonly_32",						$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.FOLDERICONS}/folder-icon_remoteonly_32.gif" },
			//{ "simple-folder-icon",								$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.FOLDERICONS}/simple-folder-icon.gif" },
			//{ "simple-folder-icon_32",							$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.FOLDERICONS}/simple-folder-icon_32.gif" },

			// status types
			{ "cm",                                             $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/cm.svg" },
			{ "co",                                             $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/co.svg" },
			{ "ds",                                             $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/ds.svg" },
			{ "dt",                                             $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/dt.svg" },
			{ "ft",                                             $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/ft.svg" },
			{ "if",                                             $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/if.svg" },
			{ "lm",                                             $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/lm.svg" },
			{ "lo",                                             $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/lo.svg" },
			{ "nv",                                             $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/nv.svg" },
			{ "ro",                                             $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/ro.svg" },
			{ "cm_640",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/cm_640.png" },
			{ "co_640",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/co_640.png" },
			{ "ds_640",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/ds_640.png" },
			{ "dt_640",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/dt_640.png" },
			{ "ft_640",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/ft_640.png" },
			{ "if_640",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/if_640.png" },
			{ "lm_640",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/lm_640.png" },
			{ "lo_640",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/lo_640.png" },
			{ "nv_640",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/nv_640.png" },
			{ "ro_640",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.STATUSFOLDER}/ro_640.png" },

			// folder icons
			{ "def_fo",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/def_fo.svg"},
			{ "def_fo_op",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/def_fo_op.svg"},
			{ "def_fo_root",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/def_fo_root.svg"},
			{ "def_fo_root_op",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/def_fo_root_op.svg"},
			
			{ "fo_db",                                          $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fo_db.svg"},
			{ "fo_db_op",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fo_db_op.svg"},
			{ "fo_loc",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fo_loc.svg"},
			{ "fo_del",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fo_del.svg"},
			{ "fo_serv",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fo_serv.svg"},
			{ "fo_serv_op",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fo_serv_op.svg"},
			{ "fo_www",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fo_www.svg"},
			{ "fo_www_op",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fo_www_op.svg"},

			{ "jpg",                                            $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/gen.svg"},
			{ "bmp",                                            $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/gen.svg"},
			{ "jpeg",                                           $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/gen.svg"},
			{ "png",                                            $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/gen.svg"},

			// extension types
			{ "4gl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/4gl.svg"},
			{ "accdb",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/accdb.svg"},
			{ "ada",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ada.svg"},
			{ "adoc",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/adoc.svg"},
			{ "advpl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/advpl.svg"},
			{ "afdesign",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/afdesign.svg"},
			{ "affectscript",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/affectscript.svg"},
			{ "afphoto",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/afphoto.svg"},
			{ "afpub",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/afpub.svg"},
			{ "agda",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/agda.svg"},
			{ "ahk",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ahk.svg"},
			{ "ai",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ai.svg"},
			{ "ai2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ai2.svg"},
			{ "al",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/al.svg"},
			{ "als",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/als.svg"},
			{ "al_dal",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/al_dal.svg"},
			{ "antlers.html",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/antlers.html.svg"},
			{ "anyscript",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/anyscript.svg"},
			{ "apex",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/apex.svg"},
			{ "apib",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/apib.svg"},
			{ "apib2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/apib2.svg"},
			{ "apl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/apl.svg"},
			{ "applescript",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/applescript.svg"},
			{ "appscript",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/appscript.svg"},
			{ "arr",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/arr.svg"},
			{ "as",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/as.svg"},
			{ "as2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/as2.svg"},
			{ "aseprite",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/aseprite.svg"},
			{ "asm",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/asm.svg"},
			{ "asp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/asp.svg"},
			{ "aspx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/aspx.svg"},
			{ "astro",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/astro.svg"},
			{ "ats",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ats.svg"},
			{ "au3",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/au3.svg"},
			{ "avif",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/avif.svg"},
			{ "avsc",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/avsc.svg"},
			{ "awk",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/awk.svg"},
			{ "bak",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/bak.svg"},
			{ "bal",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/bal.svg"},
			{ "bat",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/bat.svg"},
			{ "bats",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/bats.svg"},
			{ "bazel",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/bazel.svg"},
			{ "befunge",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/befunge.svg"},
			{ "bicep",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/bicep.svg"},
			{ "biml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/biml.svg"},
			{ "bin",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/bin.svg"},
			{ "blade",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/blade.svg"},
			{ "blend",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/blend.svg"},
			{ "blitzbasic",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/blitzbasic.svg"},
			{ "bru",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/bru.svg"},
			{ "bsq",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/bsq.svg"},
			{ "c",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/c.svg"},
			{ "c2",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/c2.svg"},
			{ "c3",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/c3.svg"},
			{ "cabal",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cabal.svg"},
			{ "cake",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cake.svg"},
			{ "capnp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/capnp.svg"},
			{ "casc",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/casc.svg"},
			{ "cddl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cddl.svg"},
			{ "ceylon",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ceylon.svg"},
			{ "cf",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cf.svg"},
			{ "cf2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cf2.svg"},
			{ "cfc",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cfc.svg"},
			{ "cfc2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cfc2.svg"},
			{ "cfm",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cfm.svg"},
			{ "cfm2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cfm2.svg"},
			{ "circom",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/circom.svg"},
			{ "cl",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cl.svg"},
			{ "class",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/class.svg"},
			{ "clj",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/clj.svg"},
			{ "cljs",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cljs.svg"},
			{ "cobol",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cobol.svg"},
			{ "coffee",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/coffee.svg"},
			{ "com_fo",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/com_fo.svg"},
			{ "com_fo_op",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/com_fo_op.svg"},
			{ "cpp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cpp.svg"},
			{ "cpp2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cpp2.svg"},
			{ "cpp3",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cpp3.svg"},
			{ "cr",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cr.svg"},
			{ "crt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/crt.svg"},
			{ "cs",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cs.svg"},
			{ "cs2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cs2.svg"},
			{ "cshtml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cshtml.svg"},
			{ "csproj",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/csproj.svg"},
			{ "css.map",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/css.map.svg"},
			{ "css",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/css.svg"},
			{ "css2.map",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/css2.map.svg"},
			{ "css2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/css2.svg"},
			{ "cuda",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cuda.svg"},
			{ "cursorrules",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/cursorrules.svg"},
			{ "c_al",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/c_al.svg"},
			{ "d",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/d.svg"},
			{ "d.ts",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/d.ts.svg"},
			{ "dal",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/dal.svg"},
			{ "dart.g",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/dart.g.svg"},
			{ "dart",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/dart.svg"},
			{ "def_fi",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/def_fi.svg"},
			{ "dhall",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/dhall.svg"},
			{ "diff",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/diff.svg"},
			{ "dj",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/dj.svg"},
			{ "doc",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/doc.svg"},
			{ "docx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/docx.svg"},
			{ "dotjs",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/dotjs.svg"},
			{ "dox",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/dox.svg"},
			{ "drawio",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/drawio.svg"},
			{ "drl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/drl.svg"},
			{ "dtd",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/dtd.svg"},
			{ "dustjs",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/dustjs.svg"},
			{ "dylan",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/dylan.svg"},
			{ "edge",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/edge.svg"},
			{ "edge2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/edge2.svg"},
			{ "eex",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/eex.svg"},
			{ "ejs",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ejs.svg"},
			{ "el",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/el.svg"},
			{ "elm",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/elm.svg"},
			{ "elm2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/elm2.svg"},
			{ "eps",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/eps.svg"},
			{ "epub",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/epub.svg"},
			{ "erb",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/erb.svg"},
			{ "erl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/erl.svg"},
			{ "erl2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/erl2.svg"},
			{ "ex",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ex.svg"},
			{ "excalidraw",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/excalidraw.svg"},
			{ "f",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/f.svg"},
			{ "falcon",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/falcon.svg"},
			{ "favicon",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/favicon.svg"},
			{ "fbx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fbx.svg"},
			{ "feature",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/feature.svg"},
			{ "fla",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fla.svg"},
			{ "flex",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/flex.svg"},
			{ "flow",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/flow.svg"},
			{ "fs",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fs.svg"},
			{ "fs2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fs2.svg"},
			{ "fsproj",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fsproj.svg"},
			{ "fthtml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/fthtml.svg"},
			{ "g4",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/g4.svg"},
			{ "gcode",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/gcode.svg"},
			{ "gd",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/gd.svg"},
			{ "gen",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/gen.svg"},
			{ "geojson",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/geojson.svg"},
			{ "glsl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/glsl.svg"},
			{ "gltf",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/gltf.svg"},
			{ "go",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/go.svg"},
			{ "gr",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/gr.svg"},
			{ "groovy",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/groovy.svg"},
			{ "groovy2",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/groovy2.svg"},
			{ "h",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/h.svg"},
			{ "haml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/haml.svg"},
			{ "hbs",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/hbs.svg"},
			{ "hbs2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/hbs2.svg"},
			{ "hjson",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/hjson.svg"},
			{ "hlsl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/hlsl.svg"},
			{ "hpp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/hpp.svg"},
			{ "hs",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/hs.svg"},
			{ "hs2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/hs2.svg"},
			{ "html",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/html.svg"},
			{ "http",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/http.svg"},
			{ "hx",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/hx.svg"},
			{ "hy",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/hy.svg"},
			{ "ice",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ice.svg"},
			{ "icl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/icl.svg"},
			{ "idr",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/idr.svg"},
			{ "idrbin",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/idrbin.svg"},
			{ "idrpkg",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/idrpkg.svg"},
			{ "imba",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/imba.svg"},
			{ "inc",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/inc.svg"},
			{ "infopath",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/infopath.svg"},
			{ "ini",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ini.svg"},
			{ "ink",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ink.svg"},
			{ "ino",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ino.svg"},
			{ "io",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/io.svg"},
			{ "iss",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/iss.svg"},
			{ "jar",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/jar.svg"},
			{ "java",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/java.svg"},
			{ "jinja",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/jinja.svg"},
			{ "jl",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/jl.svg"},
			{ "jl2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/jl2.svg"},
			{ "js.map",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/js.map.svg"},
			{ "js",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/js.svg"},
			{ "json",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/json.svg"},
			{ "json2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/json2.svg"},
			{ "json5",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/json5.svg"},
			{ "jsonld",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/jsonld.svg"},
			{ "jsonnet",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/jsonnet.svg"},
			{ "jsp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/jsp.svg"},
			{ "jss",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/jss.svg"},
			{ "jsx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/jsx.svg"},
			{ "k",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/k.svg"},
			{ "kos",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/kos.svg"},
			{ "kql",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/kql.svg"},
			{ "kt",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/kt.svg"},
			{ "kv",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/kv.svg"},
			{ "lark",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/lark.svg"},
			{ "lat",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/lat.svg"},
			{ "lean",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/lean.svg"},
			{ "less",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/less.svg"},
			{ "lime",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/lime.svg"},
			{ "liquid",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/liquid.svg"},
			{ "lisp",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/lisp.svg"},
			{ "lnk",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/lnk.svg"},
			{ "log",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/log.svg"},
			{ "lol",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/lol.svg"},
			{ "ls",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ls.svg"},
			{ "lsl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/lsl.svg"},
			{ "lua",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/lua.svg"},
			{ "luau",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/luau.svg"},
			{ "ly",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ly.svg"},
			{ "lync",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/lync.svg"},
			{ "m",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/m.svg"},
			{ "map",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/map.svg"},
			{ "marko",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/marko.svg"},
			{ "markojs",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/markojs.svg"},
			{ "matlab",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/matlab.svg"},
			{ "md",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/md.svg"},
			{ "mdb",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mdb.svg"},
			{ "mdx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mdx.svg"},
			{ "mediawiki",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mediawiki.svg"},
			{ "metal",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/metal.svg"},
			{ "mjml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mjml.svg"},
			{ "ml",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ml.svg"},
			{ "mlang",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mlang.svg"},
			{ "mli",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mli.svg"},
			{ "mm",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mm.svg"},
			{ "mojo",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mojo.svg"},
			{ "mojolicious",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mojolicious.svg"},
			{ "ms",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ms.svg"},
			{ "msg",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/msg.svg"},
			{ "mson",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mson.svg"},
			{ "mustache",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mustache.svg"},
			{ "mvt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mvt.svg"},
			{ "mvtcss",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mvtcss.svg"},
			{ "mvtjs",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/mvtjs.svg"},
			{ "nearly",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/nearly.svg"},
			{ "nginx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/nginx.svg"},
			{ "nim",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/nim.svg"},
			{ "nix",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/nix.svg"},
			{ "njsproj",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/njsproj.svg"},
			{ "npy",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/npy.svg"},
			{ "nsi",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/nsi.svg"},
			{ "nunjucks",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/nunjucks.svg"},
			{ "nut",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/nut.svg"},
			{ "ogone",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ogone.svg"},
			{ "one",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/one.svg"},
			{ "org",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/org.svg"},
			{ "ovpn",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ovpn.svg"},
			{ "p",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/p.svg"},
			{ "pas",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pas.svg"},
			{ "patch",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/patch.svg"},
			{ "pcl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pcl.svg"},
			{ "pcss",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pcss.svg"},
			{ "pddl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pddl.svg"},
			{ "pddl_happenings",								$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pddl_happenings.svg"},
			{ "pddl_plan",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pddl_plan.svg"},
			{ "pde",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pde.svg"},
			{ "pdf",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pdf.svg"},
			{ "pdf2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pdf2.svg"},
			{ "pgsql",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pgsql.svg"},
			{ "php",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/php.svg"},
			{ "php2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/php2.svg"},
			{ "php3",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/php3.svg"},
			{ "pine",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pine.svg"},
			{ "pl",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pl.svg"},
			{ "pl2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pl2.svg"},
			{ "pl6",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pl6.svg"},
			{ "plsql",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/plsql.svg"},
			{ "plsql_package",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/plsql_package.svg"},
			{ "plsql_package_body",								$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/plsql_package_body.svg"},
			{ "plsql_package_header",							$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/plsql_package_header.svg"},
			{ "plsql_package_spec",								$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/plsql_package_spec.svg"},
			{ "po",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/po.svg"},
			{ "pony",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pony.svg"},
			{ "pp",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pp.svg"},
			{ "ppt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ppt.svg"},
			{ "pptx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pptx.svg"},
			{ "prg",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/prg.svg"},
			{ "pro",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pro.svg"},
			{ "proto",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/proto.svg"},
			{ "ps1",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ps1.svg"},
			{ "ps12",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ps12.svg"},
			{ "psb",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/psb.svg"},
			{ "psd",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/psd.svg"},
			{ "psd1",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/psd1.svg"},
			{ "psd12",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/psd12.svg"},
			{ "psm1",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/psm1.svg"},
			{ "psm12",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/psm12.svg"},
			{ "pub",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pub.svg"},
			{ "pug",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pug.svg"},
			{ "puml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/puml.svg"},
			{ "purs",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/purs.svg"},
			{ "py",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/py.svg"},
			{ "pyi",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pyi.svg"},
			{ "pys",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pys.svg"},
			{ "pyx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/pyx.svg"},
			{ "q",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/q.svg"},
			{ "qbs",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/qbs.svg"},
			{ "qml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/qml.svg"},
			{ "qs",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/qs.svg"},
			{ "qvs",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/qvs.svg"},
			{ "r",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/r.svg"},
			{ "raku",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/raku.svg"},
			{ "raml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/raml.svg"},
			{ "rb",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rb.svg"},
			{ "re",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/re.svg"},
			{ "red",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/red.svg"},
			{ "rego",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rego.svg"},
			{ "res",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/res.svg"},
			{ "rest",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rest.svg"},
			{ "rexx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rexx.svg"},
			{ "rkt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rkt.svg"},
			{ "rmd",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rmd.svg"},
			{ "rnc",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rnc.svg"},
			{ "ron",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ron.svg"},
			{ "rproj",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rproj.svg"},
			{ "rq",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rq.svg"},
			{ "rs",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rs.svg"},
			{ "rss",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rss.svg"},
			{ "rules",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/rules.svg"},
			{ "safetensors",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/safetensors.svg"},
			{ "san",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/san.svg"},
			{ "sas",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sas.svg"},
			{ "sass",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sass.svg"},
			{ "sbt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sbt.svg"},
			{ "scad",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/scad.svg"},
			{ "scala",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/scala.svg"},
			{ "sci",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sci.svg"},
			{ "scss",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/scss.svg"},
			{ "scss2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/scss2.svg"},
			{ "sdlang",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sdlang.svg"},
			{ "sh",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sh.svg"},
			{ "shader",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/shader.svg"},
			{ "sketch",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sketch.svg"},
			{ "sl",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sl.svg"},
			{ "slang",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/slang.svg"},

			{ "sldasm",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldasm.svg" },
			{ "slddrw",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/slddrw.svg" },
			{ "sldprt",                                         $"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sldprt.svg" },

			{ "slim",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/slim.svg"},
			{ "slint",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/slint.svg"},
			{ "sln",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sln.svg"},
			{ "sln2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sln2.svg"},
			{ "sol",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sol.svg"},
			{ "sqf",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sqf.svg"},
			{ "sql",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sql.svg"},
			{ "sqlite",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sqlite.svg"},
			{ "sss",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sss.svg"},
			{ "st.css",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/st.css.svg"},
			{ "stan",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/stan.svg"},
			{ "stata",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/stata.svg"},
			{ "storyboard",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/storyboard.svg"},
			{ "styl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/styl.svg"},
			{ "stylish-haskell",								$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/stylish-haskell.svg"},
			{ "sublime",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sublime.svg"},
			{ "sv",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/sv.svg"},
			{ "svelte",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/svelte.svg"},
			{ "svg",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/svg.svg"},
			{ "swf",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/swf.svg"},
			{ "swift",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/swift.svg"},
			{ "swig",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/swig.svg"},
			{ "tag",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tag.svg"},
			{ "tcl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tcl.svg"},
			{ "templ",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/templ.svg"},
			{ "tera",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tera.svg"},
			{ "test.js",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/test.js.svg"},
			{ "test.ts",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/test.ts.svg"},
			{ "tex",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tex.svg"},
			{ "textile",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/textile.svg"},
			{ "tf",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tf.svg"},
			{ "tl",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tl.svg"},
			{ "toml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/toml.svg"},
			{ "tpl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tpl.svg"},
			{ "tres",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tres.svg"},
			{ "ts",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ts.svg"},
			{ "tsbuildinfo",									$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tsbuildinfo.svg"},
			{ "tscn",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tscn.svg"},
			{ "tsx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tsx.svg"},
			{ "tt",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/tt.svg"},
			{ "ttcn",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/ttcn.svg"},
			{ "twig",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/twig.svg"},
			{ "txt",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/txt.svg"},
			{ "u",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/u.svg"},
			{ "uiua",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/uiua.svg"},
			{ "v",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/v.svg"},
			{ "vala",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vala.svg"},
			{ "vapi",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vapi.svg"},
			{ "vash",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vash.svg"},
			{ "vb",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vb.svg"},
			{ "vba",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vba.svg"},
			{ "vbhtml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vbhtml.svg"},
			{ "vbproj",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vbproj.svg"},
			{ "vcxproj",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vcxproj.svg"},
			{ "vhd",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vhd.svg"},
			{ "vm",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vm.svg"},
			{ "vscode",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vscode.svg"},
			{ "vsix",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vsix.svg"},
			{ "vto",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vto.svg"},
			{ "vue",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vue.svg"},
			{ "vy",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/vy.svg"},
			{ "wasm",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/wasm.svg"},
			{ "wgsl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/wgsl.svg"},
			{ "wikitext",										$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/wikitext.svg"},
			{ "wit",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/wit.svg"},
			{ "wl",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/wl.svg"},
			{ "wurst",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/wurst.svg"},
			{ "wxml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/wxml.svg"},
			{ "wxss",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/wxss.svg"},
			{ "wy",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/wy.svg"},
			{ "xfl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/xfl.svg"},
			{ "xib",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/xib.svg"},
			{ "xliff",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/xliff.svg"},
			{ "xls",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/xls.svg"},
			{ "xlsx",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/xlsx.svg"},
			{ "xml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/xml.svg"},
			{ "xq",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/xq.svg"},
			{ "xsl",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/xsl.svg"},
			{ "y",												$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/y.svg"},
			{ "yaml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/yaml.svg"},
			{ "yang",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/yang.svg"},
			{ "yml",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/yml.svg"},
			{ "zig",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/zig.svg"},
			{ "zip",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/zip.svg"},
			{ "zip2",											$"{SB.ASSETSPREFIX}{SB.ASSETSFOLDER}/{SB.ICONFOLDER}/zip2.svg"},
		};
		LoadInLocalDictionary();
	}
	internal static async void LoadInLocalDictionary()
	{
		StorageFolder assetFolder;
		StorageFolder imageFolder;

		string relativeDir = $"{SB.ASSETSFOLDER}/{SB.IMAGEFOLDER}";
		string msDir = $"{SB.LOCALPREFIX}/{relativeDir}";

		assetFolder = await Storage.CreateFolderAsync(SB.ASSETSFOLDER, CreationCollisionOption.OpenIfExists);
		imageFolder = await assetFolder.CreateFolderAsync(SB.IMAGEFOLDER, CreationCollisionOption.OpenIfExists);
		

		StorageFile[] files = [.. await imageFolder.GetFilesAsync()];
		foreach (var file in files)
		{
			AssetMap.Add(file.Name, $"{msDir}/{file.Name}.{file.FileType.ToLower()}");
		}
	}
	private static IImageProvider GetProvider(Dictionary<string, string>? assetmap = null)
	{
		var os = Environment.OSVersion.Version;
#pragma warning disable CA1416 // Validate platform compatibility
		return os.Major >= 10
			? new AssetsImageProvider(assetmap)
			: new ImageListProvider();
#pragma warning restore CA1416 // Validate platform compatibility
	}
	public static IImageProvider ImageProvider 
	{ 
		get
		{
			field ??= GetProvider(AssetMap);
			return field;
		}
	}
	public static ImageSource? GetImage(string key)							=> ImageProvider.GetImage(key);
	public static Task<ImageSource?> GetImageAsync(string key)				=> ImageProvider.GetImageAsync(key);
	public static BitmapImage? GetBitmapFromBytes(byte[] imgBytes)
	{
		using var ms = new MemoryStream(imgBytes);
		var img = new BitmapImage();
		img.SetSource(ms.AsRandomAccessStream());
		return img;
	}
	public static System.Drawing.Bitmap? GetBitmap(string key)				=> ImageProvider.GetBitmap(key);
	public static IEnumerable<string> GetAvailableKeys()					=> ImageProvider.GetAvailableKeys();
	public static void SetImage(string key, byte[] imgBytes)				=> ImageProvider.SetImage(key, imgBytes);
	public static void SetImage(string key, SoftwareBitmap img)
	{
		if (ImageProvider is AssetsImageProvider aip)
		{
			aip.SetImage(key, img);
		}
	}
	public async static Task<byte[]> GetImageBytes(BitmapImage img)
	{
		var streamref = RandomAccessStreamReference.CreateFromUri(img.UriSource);
		using var stream = await streamref.OpenReadAsync();
		byte[] buffer = new byte[stream.Size];
		await stream.ReadAsync(buffer.AsBuffer(), (uint)stream.Size, InputStreamOptions.None);
		return buffer;
	}
}