[options]
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
data_dir = /mnt/datastore
addons_path = /opt/odoo/addons,/home/moony/dev/hack_odoo_dev/Odoo/addons
without_demo = True
default_productivity_apps = True
logfile = /var/log/odoo/odoo.log
