<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
	<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>HackPDM</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platform>x64</Platform>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <WindowsTargetPlatformVersion>10.0.26100.0</WindowsTargetPlatformVersion>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <DefineConstants Condition="!('$(WindowsTargetPlatformVersion)' &gt;= '10.0.10240.0')">WINDOWS_LEGACY</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="UI\Forms\Hack\home.xaml" />
    <None Remove="UI\Forms\Helper\MessageBoxWindow.xaml" />
    <None Remove="UI\Forms\Settings\NotLoggedIn.xaml" />
  </ItemGroup>
    <ItemGroup>
		<ProjectReference Include="..\HackPDM.Infrastructure\HackPDM.Infrastructure.csproj" />
    </ItemGroup>

  <ItemGroup>
    
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" />
    <PackageReference Include="Meziantou.Framework.Win32.CredentialManager" Version="1.7.15" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.3.2" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.1" />
    <PackageReference Include="System.Reactive" Version="7.0.0-preview.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs.backup">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx.backup</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
	  <Content Include="Assets\**\*.*">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx.backup">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Page Update="UI\Forms\Settings\NotLoggedIn.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Hack\Home.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Helper\MessageBox.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Helper\MessageBoxWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Forms\Hack\HackFileManager.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Forms\Hack\HackSettings.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Forms\Odoo\OdooFileTypeManager.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Forms\Odoo\OdooSettings.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Forms\Odoo\SearchOdoo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Forms\Settings\ProfileManager.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Forms\Settings\StatusDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Forms\Settings\StatusSettings.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Forms\Settings\ThemeSettings.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Hack\HackFileManager.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Hack\HackSettings.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Odoo\OdooFileTypeManager.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Odoo\OdooSettings.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Odoo\SearchOdoo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Settings\ProfileManager.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Settings\StatusDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\Forms\Settings\ApplicationSettingsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="SolidWorks.Interop.sldworks">
      <HintPath>..\HackPDM.Infrastructure\lib\SolidWorks.Interop.sldworks.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorks.Interop.swcommands">
      <HintPath>..\HackPDM.Infrastructure\lib\SolidWorks.Interop.swcommands.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorks.Interop.swconst">
      <HintPath>..\HackPDM.Infrastructure\lib\SolidWorks.Interop.swconst.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorks.Interop.swdocumentmgr">
      <HintPath>..\HackPDM.Infrastructure\lib\SolidWorks.Interop.swdocumentmgr.dll</HintPath>
    </Reference>
    <Reference Include="XmlRpcCs">
      <HintPath>..\HackPDM.Infrastructure\lib\XmlRpcCs.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <ApplicationIcon>Assets\hackpdm-icon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>