<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsRoslynComponent>true</IsRoslynComponent>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<OutputItemType>Analyzer</OutputItemType>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" PrivateAssets="all" /> 
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<!-- <ProjectReference Include="..\HackPDM.Abstractions\HackPDM.Abstractions.csproj" /> -->
		<ProjectReference Include="..\HackPDM.Shared\HackPDM.Shared.csproj" >
			<Private>true</Private>
			<CopyLocal>true</CopyLocal>
		</ProjectReference>
	</ItemGroup>

</Project>
