using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

using HackPDM.SchemaGenerator.GeneratedTypes;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HackPDM.SchemaGenerator;

[Generator]
public sealed class OdooSchemaGenerator : IIncrementalGenerator
{
	public void Initialize( IncrementalGeneratorInitializationContext context )
	{
		var classDeclarations = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) =>
					node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
				transform: static (ctx, _) =>
					(ClassDeclarationSyntax)ctx.Node
			)
			.Where(static cls => cls is not null);

		var compilationAndClasses =
			context.CompilationProvider.Combine(classDeclarations.Collect());

		context.RegisterSourceOutput( compilationAndClasses, Generate );
	}

	private static void Generate(
		SourceProductionContext context,
		(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes) input )
	{
		var (compilation, classes) = input;

		var modelEntries = new List<(string FullName, string Name, string Namespace)>();
		var modelAttrs = new List<(string name, string DbName)>();

		foreach( var classSyntax in classes )
		{
			var semanticModel = compilation.GetSemanticModel(classSyntax.SyntaxTree);
			if( semanticModel.GetDeclaredSymbol( classSyntax ) is not INamedTypeSymbol classSymbol )
				continue;

			var modelAttr = classSymbol.GetAttributes()
				.FirstOrDefault(a =>
					a.AttributeClass?.ToDisplayString() ==
					"HackPDM.Shared.OdooAttributes.OdooModelAttribute");

			if( modelAttr is null )
				continue;

			var fullName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			var name = classSymbol.Name;
			var ns = classSymbol.ContainingNamespace.ToDisplayString();

			modelAttrs.Add( (name, ( string )modelAttr.ConstructorArguments[ 1 ].Value!) );
			modelEntries.Add( (fullName, name, ns) );

			var props = CollectProperties(classSymbol);

			EmitModelBundle( context, classSymbol, props );
		}

		EmitHpBaseModelPartial( context, modelAttrs );              // generate the model HpModelDictionaryGen
		EmitGenericFacade( context, modelEntries );					// generate the generic mapper
		EmitGenericFieldSelectionFacade( context, modelEntries );	// generate field selector
	}

	private static List<OdooPropertyGen> CollectProperties( INamedTypeSymbol classSymbol )
	{
		var props = new List<OdooPropertyGen>();

		foreach( var prop in classSymbol.GetMembers().OfType<IPropertySymbol>() )
		{
			var attr = prop.GetAttributes()
				.FirstOrDefault(a =>
					a.AttributeClass?.ToDisplayString() ==
					"HackPDM.Shared.OdooAttributes.OdooPropAttribute");

			if( attr is null )
				continue;

			if( attr.ConstructorArguments.Length < 2 )
				continue;

			if( attr.ConstructorArguments[ 0 ].Value is not int typeVal )
				continue;

			if( attr.ConstructorArguments[ 1 ].Value is not string fieldName )
				continue;

			props.Add( new OdooPropertyGen(
				( OdooFieldType )Enum.ToObject( typeof( OdooFieldType ), typeVal ),
				fieldName,
				prop ) );
		}

		return props;
	}

	private static void EmitModelBundle(
		SourceProductionContext context,
		INamedTypeSymbol classSymbol,
		List<OdooPropertyGen> props )
	{
		var className = classSymbol.Name;
		var ns = classSymbol.ContainingNamespace.ToDisplayString();

		// inbound assignments
		var assignmentLines = string.Join(",\n            ",
			props.Select(p =>
			{
				var type = p.property.Type;
				var clrType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

				bool isNullableReferenceType =
					!type.IsValueType && p.property.NullableAnnotation == NullableAnnotation.Annotated;

				string castType = clrType;
				if (isNullableReferenceType)
					castType = $"{clrType}?";

				var fieldTypeName = $"(global::HackPDM.Shared.GlobalData.OdooFieldType.{p.odooType})";

				var convertCall =
					$"({castType})global::HackPDM.Infrastructure.Odoo.OdooFieldHelpers.Convert({fieldTypeName}, value)";

				return
					$"[\"{p.odooFieldName}\"] = (model, value) => model.{p.property.Name} = {convertCall}";
			}));

		// outbound entries
		var outboundLines = string.Join(",\n            ",
			props.Select(p =>
			{
				var expr = GenerateOutboundExpression(p, "model");
				return $"[\"{p.odooFieldName}\"] = {expr}";
			}));

		// field names (property names)
		var fieldNames = string.Join(",\n        ",
			props.Select(p => $"\"{p.property.Name}\""));

		var source = $$"""
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;

namespace {{ns}};

public static partial class OdooAssignments_{{className}}
{
    public static readonly global::System.Collections.Generic.Dictionary<string, global::System.Action<{{ns}}.{{className}}, object?>> Map =
        new()
        {
            {{assignmentLines}}
        };

    public static global::System.Collections.Generic.Dictionary<string, object?> ToOdoo({{ns}}.{{className}} model) =>
        new()
        {
            {{outboundLines}}
        };
}

public static partial class OdooFieldSelection_{{className}}
{
    internal static readonly string[] ModelFields = new[]
    {
        {{fieldNames}}
    };

    public static string[] GetFields(
        string[]? excluded = null,
        string[]? included = null,
        string[]? insert = null) =>
        global::HackPDM.Infrastructure.Odoo.Models.OdooFieldSelector.Select(
            ModelFields, excluded, included, insert);
}


public partial class {{className}}
{
    public override global::System.Collections.Generic.Dictionary<string, object?> ToOdoo() =>
        global::HackPDM.Infrastructure.Odoo.Models.OdooAssignments_{{className}}.ToOdoo(this);
}

""";

		context.AddSource( $"{className}_OdooModelBundle.g.cs", source );
	}
	private static void EmitGenericFieldSelectionFacade(
	SourceProductionContext context,
	List<(string FullName, string Name, string Namespace)> models )
	{
		var cases = string.Join("\n            ",
		models.Select(m =>
			$"\"{m.Name}\" => (excluded, included, insert) => " +
			$"HackPDM.Infrastructure.Odoo.Models.OdooFieldSelection_{m.Name}.GetFields(excluded, included, insert),"));

		var source = $$"""
// <auto-generated />
namespace HackPDM.Infrastructure.Odoo.Models;

internal static class OdooFieldSelectionCache<TModel>
{
    public static readonly System.Func<string[]?, string[]?, string[]?, string[]> GetFields =
        Resolve();

    private static System.Func<string[]?, string[]?, string[]?, string[]> Resolve()
    {
        var t = typeof(TModel);

        return t.Name switch
        {
            {{cases}}
            _ => (_, _, _) => throw new System.InvalidOperationException(
                $"No OdooFieldSelection class generated for {t.Name}")
        };
    }
}
""";

		context.AddSource( "OdooFieldSelection_GenericFacade.g.cs", source );
	}

	private static string GenerateOutboundExpression( OdooPropertyGen p, string modelVar )
	{
		var prop = p.property.Name;
		var access = $"{modelVar}.{prop}";

		return p.odooType switch
		{
			OdooFieldType.Char or OdooFieldType.Text =>
				access,

			OdooFieldType.Integer =>
				$"(object?){access}",

			OdooFieldType.Float =>
				$"global::System.Convert.ToDouble({access})",

			OdooFieldType.Boolean =>
				$"({access} is true ? 1 : 0)",

			OdooFieldType.Date =>
				$"{access}?.ToString(\"yyyy-MM-dd\")",

			OdooFieldType.DateTime =>
				$"{access}?.ToString(\"yyyy-MM-ddTHH:mm:ss\")",

			OdooFieldType.Many2One =>
				$"{access}?.Id",

			OdooFieldType.One2Many or OdooFieldType.Many2Many =>
				$$"""
                {{access}} is null 
                    ? null 
                    : new object[]
                    {
                        new object[]
                        {
                            6,
                            0,
                            {{access}}.Select(x => x.Id).ToArray()
                        }
                    }
                """,

			_ => access
		};
	}

	private static void EmitHpBaseModelPartial(
		SourceProductionContext context,
		List<(string name, string DbName)> entries )
	{
		var dictEntries = string.Join(",\n        ",
			entries.Select(e => $"{{ nameof({e.name}), \"{e.DbName}\" }}"));

		var source = $$"""
// <auto-generated />
namespace HackPDM.Infrastructure.Odoo.Models;

public partial class HpBaseModelTransport
{
    public static readonly global::System.Collections.Generic.Dictionary<string, string> HpModelDictionaryGen =
        new()
        {
            {{dictEntries}}
        };
}
""";

		context.AddSource(
			"HpBaseModelTransport_HpModelDictionary.g.cs",
			source
		);
	}

	private static void EmitGenericFacade(
		SourceProductionContext context,
		List<(string FullName, string Name, string Namespace)> models )
	{
		var cases = string.Join("\n            ",
			models.Select(m =>
				$"\"{m.Name}\" => (global::System.Collections.Generic.Dictionary<string, global::System.Action<TModel, object?>>)(object)OdooAssignments_{m.Name}.Map,"));

		var source = $$"""
// <auto-generated />
namespace HackPDM.Infrastructure.Odoo.Models;
        
public static class OdooAssignments<TModel>
{
    public static global::System.Collections.Generic.Dictionary<string, global::System.Action<TModel, object?>> Map =>
        OdooAssignmentsCache<TModel>.Map;
}

internal static class OdooAssignmentsCache<TModel>
{
    public static readonly global::System.Collections.Generic.Dictionary<string, global::System.Action<TModel, object?>> Map =
        Resolve();

    private static global::System.Collections.Generic.Dictionary<string, global::System.Action<TModel, object?>> Resolve()
    {
        var t = typeof(TModel);

        return t.Name switch
        {
            {{cases}}
            _ => throw new global::System.InvalidOperationException($"No OdooAssignments class generated for {t.Name}")
        };
    }
}
""";

		context.AddSource( "OdooAssignments_GenericFacade.g.cs", source );
	}
}

