using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using HackPDM.SchemaGenerator.GeneratedTypes;
using HackPDM.Shared.General;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HackPDM.SchemaGenerator;

[Generator]
public sealed class SchemaGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var classDeclarations = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) =>
					node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
				transform: static (ctx, _) =>
					(ClassDeclarationSyntax)ctx.Node
			)
			.Where(static cls => cls is not null);

		var compilationAndClasses =
			context.CompilationProvider.Combine(classDeclarations.Collect());

		context.RegisterSourceOutput(compilationAndClasses, Generate);
	}
	private static string GenerateEnum( IEnumerable<ColorCsvRow> rows )
	{
		var sb = new StringBuilder();

		sb.AppendLine( "namespace HackPDM.UI.Types;" );
		sb.AppendLine( "public enum ColorNames : uint" );
		sb.AppendLine( "{" );

		foreach( var row in rows.Where(r => r.GoodName) )
		{
			string enumName = Help.ToEnumName(row.Name);
			uint value = Help.HexToUint(row.Hex);

			sb.AppendLine( $"	{enumName} = 0x{value:X8}," );
		}
		sb.AppendLine( "}" );
		return sb.ToString();
	}
	private static void Generate(
		SourceProductionContext context,
		(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes) input)
	{
		var (compilation, classes) = input;

		var modelEntries = new List<(string FullName, string Name, string Namespace)>();
		var modelAttrs = new List<(string FullName, string DbName)>();
		foreach (var classSyntax in classes)
		{
			var semanticModel = compilation.GetSemanticModel(classSyntax.SyntaxTree);
			if (semanticModel.GetDeclaredSymbol(classSyntax) is not INamedTypeSymbol classSymbol)
				continue;

			var modelAttr = classSymbol.GetAttributes()
				.FirstOrDefault(a =>
					a.AttributeClass?.ToDisplayString() ==
					"HackPDM.Shared.OdooAttributes.OdooModelAttribute");

			if (modelAttr is null)
				continue;

			var fullName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			var name = classSymbol.Name;
			var ns = classSymbol.ContainingNamespace.ToDisplayString();

			modelAttrs.Add((fullName, (string)modelAttr.ConstructorArguments[1].Value!));
			modelEntries.Add((name, name, ns));

			var props = CollectProperties(classSymbol);
			EmitAssignmentSchema(context, classSymbol, props);
		}
		EmitHpBaseModelPartial(context, modelAttrs);
		EmitGenericFacade(context, modelEntries);
	}
	private static void EmitHpBaseModelPartial(
	SourceProductionContext context,
	List<(string name, string DbName)> entries)
	{
		var dictEntries = string.Join(",\n        ",
			entries.Select(e => $"{{ nameof({e.name}), \"{e.DbName}\" }}"));

		var source = $$"""
// <auto-generated />
namespace HackPDM.Infrastructure.Odoo.Models;

public partial class HpBaseModelTransport
{
    public static readonly global::System.Collections.Generic.Dictionary<string, string> HpModelDictionaryGen =
    new()
    {
    {{dictEntries}}
    };
}
""";

		context.AddSource(
			"HpBaseModelTransport_HpModelDictionary.g.cs",
			source
		);
	}

	private static List<OdooPropertyGen> CollectProperties(INamedTypeSymbol classSymbol)
	{
		var props = new List<OdooPropertyGen>();

		foreach (var prop in classSymbol.GetMembers().OfType<IPropertySymbol>())
		{
			var attr = prop.GetAttributes()
				.FirstOrDefault(a =>
					a.AttributeClass?.ToDisplayString() ==
					"HackPDM.Shared.OdooAttributes.OdooPropAttribute");

			if (attr is null)
				continue;

			if (attr.ConstructorArguments.Length < 2)
				continue;

			if (attr.ConstructorArguments[0].Value is not int typeVal)
				continue;

			if (attr.ConstructorArguments[1].Value is not string fieldName)
				continue;

			props.Add(new OdooPropertyGen((OdooFieldType)Enum.ToObject(typeof(OdooFieldType), typeVal), fieldName, prop));
		}

		return props;
	}

	private static void EmitAssignmentSchema(
		SourceProductionContext context,
		INamedTypeSymbol classSymbol,
		List<OdooPropertyGen> props)
	{
		var className = classSymbol.Name;
		var ns = classSymbol.ContainingNamespace.ToDisplayString();

		var assignmentLines = string.Join(",\n            ",
			props.Select(p =>
			{
				var type = p.property.Type;
				var clrType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

				bool isNullableValueType =
					type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

				bool isNullableReferenceType =
					!type.IsValueType && p.property.NullableAnnotation == NullableAnnotation.Annotated;

				string castType = clrType;

				if (isNullableReferenceType)
					castType = $"{clrType}?";

				var fieldTypeName = $"(global::HackPDM.Shared.GlobalData.OdooFieldType.{p.odooType})";

				var convertCall =
					$"({castType})global::HackPDM.Infrastructure.Odoo.OdooFieldHelpers.Convert({fieldTypeName}, value)";

				return
					$"[\"{p.odooFieldName}\"] = (model, value) => model.{p.property.Name} = {convertCall}";
			}));

		var source = $$"""
// <auto-generated />
namespace HackPDM.Infrastructure.Odoo.Models;
        
public static partial class OdooAssignments_{{className}}
{
    public static readonly global::System.Collections.Generic.Dictionary<string, global::System.Action<{{ns}}.{{className}}, object?>> Map =
    new()
    {
    {{assignmentLines}}
    };
}
        
""";

		context.AddSource($"{className}_OdooAssignments.g.cs", source);
	}
	private static void EmitGenericFacade(
		SourceProductionContext context,
		List<(string FullName, string Name, string Namespace)> models)
	{
		var cases = string.Join("\n            ",
			models.Select(m =>
				$"\"{m.Name}\" => (global::System.Collections.Generic.Dictionary<string, global::System.Action<TModel, object?>>)(object)OdooAssignments_{m.Name}.Map,"));

		var source = $$"""
// <auto-generated />
namespace HackPDM.Infrastructure.Odoo.Models;
        
public static class OdooAssignments<TModel>
{
	public static global::System.Collections.Generic.Dictionary<string, global::System.Action<TModel, object?>> Map =>
		OdooAssignmentsCache<TModel>.Map;
}

internal static class OdooAssignmentsCache<TModel>
{
	public static readonly global::System.Collections.Generic.Dictionary<string, global::System.Action<TModel, object?>> Map =
		Resolve();

	private static global::System.Collections.Generic.Dictionary<string, global::System.Action<TModel, object?>> Resolve()
	{
		var t = typeof(TModel);

		return t.Name switch
		{
		{{cases}}
			_ => throw new global::System.InvalidOperationException($"No OdooAssignments class generated for {t.Name}")
		};
	}
}
""";

		context.AddSource("OdooAssignments_GenericFacade.g.cs", source);
	}
}
