// using System;
// using System.Collections.Generic;
// using System.Collections.Immutable;
// using System.Reflection;
// using System.Text;
//
// using HackPDM.SchemaGenerator.GeneratedTypes;
// using HackPDM.Shared.GlobalData;
//
// using Microsoft.CodeAnalysis;
// using Microsoft.CodeAnalysis.CSharp.Syntax;
//
// namespace HackPDM.SchemaGenerator;
//
// #pragma warning disable RS1038 // Compiler extensions should be implemented in assemblies with compiler-provided references
// [Generator]
// #pragma warning restore RS1038 // Compiler extensions should be implemented in assemblies with compiler-provided references
// public class SchemaGenerator : IIncrementalGenerator
// {
// 	public void Initialize(IncrementalGeneratorInitializationContext context)
// 	{
// 		var modelClasses = context.SyntaxProvider
// 			.CreateSyntaxProvider(
// 				predicate: static (node, _) =>
// 					node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
// 				transform: static (ctx, _) =>
// 					(ClassDeclarationSyntax)ctx.Node
// 			)
// 			.Where(static cls => cls is not null);
//
// 		var compilationAndClasses =
// 			context.CompilationProvider.Combine(modelClasses.Collect());
//
// 		context.RegisterSourceOutput(compilationAndClasses, GenerateModelSchema);
// 	}
//
// 	private static void GenerateModelSchema(
// 	SourceProductionContext context,
// 	(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes) input)
// 	{
// 		var (compilation, classes) = input;
//
// 		var entries = new List<(string TypeName, string DbName)>();
//
// 		foreach (var classSyntax in classes)
// 		{
// 			var model = compilation.GetSemanticModel(classSyntax.SyntaxTree);
// 			var classSymbol = model.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;
//
// 			if (classSymbol is null)
// 				continue;
//
// 			// Look for [OdooModel]
// 			var modelAttr = classSymbol.GetAttributes()
// 				.FirstOrDefault(a => a.AttributeClass?.Name == "OdooModelAttribute");
//
// 			if (modelAttr is null)
// 				continue; // not an Odoo model
//
// 			var dbName = (string)modelAttr.ConstructorArguments[0].Value!;
// 			var typeName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
// 			// Now collect fields
// 			// var fields = CollectFields(classSymbol);
// 			entries.Add((typeName, dbName));
// 		}
// 		EmitHpBaseModelPartial(context, entries);
// 	}
// 	private static void EmitHpBaseModelPartial(
// 	SourceProductionContext context,
// 	List<(string TypeName, string DbName)> entries)
// 	{
// 		var dictEntries = string.Join(",\n        ",
// 			entries.Select(e => $"{{ typeof({e.TypeName}), \"{e.DbName}\" }}"));
//
// 		var source = $$"""
// // <auto-generated />
// namespace HackPDM.Domain.OdooModels.Models
// {
//     public partial class HpBaseModel
//     {
//         protected static readonly global::System.Collections.Generic.Dictionary<global::System.Type, string> HpModelDictionaryGen =
//             new()
//             {
//                 {{dictEntries}}
//             };
//     }
// }
// """;
//
// 		context.AddSource(
// 			"OdooModels/Models/Generated/HpBaseModel_HpModelDictionary.g.cs",
// 			source
// 		);
//
// 	}
//
// 	private static List<OdooFieldGen> CollectFields(INamedTypeSymbol classSymbol)
// 	{
// 		var fields = new List<OdooFieldGen>();
//
// 		foreach (var member in classSymbol.GetMembers().OfType<IFieldSymbol>())
// 		{
// 			var fieldAttr = member.GetAttributes()
// 				.FirstOrDefault(a => a.AttributeClass?.Name == "OdooFieldAttribute");
//
// 			if (fieldAttr is null)
// 				continue;
//
// 			var fieldValue = (OdooFieldType)fieldAttr.ConstructorArguments[0].Value!;
//
// 			fields.Add(new OdooFieldGen(fieldValue));
// 		}
//
// 		return fields;
// 	}
// 	private static void EmitSchema(
// 	SourceProductionContext context,
// 	INamedTypeSymbol classSymbol,
// 	string odooModelName,
// 	List<OdooFieldGen> fields)
// 	{
// 		var className = classSymbol.Name;
// 		var ns = classSymbol.ContainingNamespace.ToDisplayString();
//
// 		var fieldLines = string.Join(",\n        ",
// 			fields.Select(f => $"[\"{f.odooType}\"] = \""));
//
// //		var source = $$"""
// //// <auto-generated />
// //namespace HackPDM.Generated
// //{
// //    public static partial class OdooSchemas
// //    {
// //        public static readonly Dictionary<string, Dictionary<string, string>> Models =
// //            new()
// //            {
// //                ["{{odooModelName}}"] = new Dictionary<string, string>
// //                {
// //                    {{fieldLines}}
// //                }
// //            };
// //    }
// //}
// //""";
//
// //		context.AddSource($"{className}_Schema.g.cs", source);
// 	}
//
//
// }

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace HackPDM.SchemaGenerator;

[Generator]
public class OdooModelConvertGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Find all interfaces with [OdooModel]
        var modelInterfaces = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidate(node),
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        // Step 2: Combine with compilation
        var compilationAndModels = context.CompilationProvider.Combine(modelInterfaces.Collect());

        // Step 3: Generate
        context.RegisterSourceOutput(compilationAndModels, static (spc, source) =>
        {
            var (compilation, models) = source;

            foreach (var iface in models!)
            {
                GenerateForInterface(spc, compilation, iface!);
            }
        });
    }

    private static bool IsCandidate(SyntaxNode node)
        => node is InterfaceDeclarationSyntax ids &&
           ids.AttributeLists.Count > 0;

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext ctx)
    {
        var ifaceSyntax = (InterfaceDeclarationSyntax)ctx.Node;

        foreach (var attrList in ifaceSyntax.AttributeLists)
        {
            foreach (var attr in attrList.Attributes)
            {
                var symbol = ctx.SemanticModel.GetSymbolInfo(attr).Symbol;
                if (symbol is IMethodSymbol ms &&
                    ms.ContainingType.Name == "OdooModelAttribute")
                {
                    return ctx.SemanticModel.GetDeclaredSymbol(ifaceSyntax) as INamedTypeSymbol;
                }
            }
        }

        return null;
    }

    private static void GenerateForInterface(
        SourceProductionContext context,
        Compilation compilation,
        INamedTypeSymbol iface)
    {
        string ifaceName = iface.Name; // e.g., IHpCategoryModel
        string modelName = ResolveModelName(ifaceName); // e.g., HpCategory

        // Find the concrete class in the compilation
        var modelType = compilation.GetTypeByMetadataName(iface.ContainingNamespace + "." + modelName);
        if (modelType is null)
        {
            // No class found — skip
            return;
        }

        // Collect properties
        var props = iface.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.SetMethod is not null)
            .ToList();

        // Generate source
        var source = GenerateConvertSource(iface, modelType, props);

        context.AddSource($"{modelName}_Convert.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string ResolveModelName(string ifaceName)
    {
        // IHpCategoryModel → HpCategory
        if (!ifaceName.StartsWith("I") || !ifaceName.EndsWith("Model"))
            return ifaceName;

        return ifaceName.Substring(1, ifaceName.Length - "Model".Length - 1);
    }

    private static string GenerateConvertSource(
        INamedTypeSymbol iface,
        INamedTypeSymbol model,
        List<IPropertySymbol> props)
    {
        var ns = model.ContainingNamespace.ToDisplayString();
        var ifaceName = iface.ToDisplayString();
        var modelName = model.Name;

        var sb = new StringBuilder($@"
using System;

namespace {ns}
{{
    public partial class {modelName} : IHpModelConvert<{ifaceName}, {modelName}>
    {{
        public {modelName} Convert({ifaceName} source)
        {{
            return new {modelName}
            {{
");

        foreach (var p in props)
        {
            sb.AppendLine($"                {p.Name} = source.{p.Name},");
        }

        sb.AppendLine($@"            }};
        }}
    }}
}}");

        return sb.ToString();
    }
}
