name: Build and Deploy

on:
  push:
    branches:
      - justinOdooIntegration

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'
    
    - name: Install .NET Framework Developer Pack
      run: |
        choco install microsoft-build-tools -y
        choco install netfx-4.8-devpack -y

    - name: Restore NuGet packages
      run: nuget restore ./HackPDM_CSharp/HackPDM_CSharp.sln

    - name: Change directory to project folder
      run: cd ./HackPDM_CSharp

    - name: Restore dependencies
      run: |
        cd ./HackPDM_CSharp
        dotnet restore

    - name: Build project
      run: |
        cd ./HackPDM_CSharp
        dotnet build --configuration GitRelease

    - name: Publish project
      run: |
        cd ./HackPDM_CSharp
        dotnet publish --configuration GitRelease --output ../publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./HackPDM_CSharp/publish

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git clone --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
        cp -r ./HackPDM_CSharp/publish/* gh-pages/
        cd gh-pages
        git add .
        git commit -m "Deploy new version"
        git push
